name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.yml'

env:
  PRIMARY_NODE_VERSION: 12

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Use Node.js ${{ env.PRIMARY_NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.PRIMARY_NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
